version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: users-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - users-db-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
    container_name: app-server
    environment:
      HTTP_PORT: "${HTTP_PORT}"
      JWT_SECRET: "${JWT_SECRET}"
      JWT_EXPIRES_IN_SEC: "${JWT_EXPIRES_IN_SEC}"
      DATABASE_URL: "${DATABASE_URL}"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  users-db-data:
