// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/csr": {
            "get": {
                "description": "Returns all pending Certificate Signing Requests",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CSR"
                ],
                "summary": "List all pending CSR requests",
                "responses": {
                    "200": {
                        "description": "List of CSR requests",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.CSRRequest"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/csr/approve": {
            "post": {
                "description": "Approves a CSR request by its ID and signs the certificate",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CSR"
                ],
                "summary": "Approve a CSR request",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "CSR Request ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Signed certificate",
                        "schema": {
                            "$ref": "#/definitions/model.CsrRequest"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/csr": {
            "post": {
                "description": "Accepts a Certificate Signing Request from an agent",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CSR"
                ],
                "summary": "Accept a new CSR request",
                "parameters": [
                    {
                        "description": "CSR Request payload",
                        "name": "csr",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CSRRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Signed certificate",
                        "schema": {
                            "$ref": "#/definitions/dto.CertificateResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/csr/signed": {
            "get": {
                "description": "Returns the signed certificate for the given CSR ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CSR"
                ],
                "summary": "Get signed certificate by CSR ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "CSR ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Signed certificate",
                        "schema": {
                            "$ref": "#/definitions/dto.CertificateResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid CSR ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/sms/list": {
            "get": {
                "description": "Returns the list of all sent SMS",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SMS"
                ],
                "summary": "Get all SMS",
                "responses": {
                    "200": {
                        "description": "List of sent SMS",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.SmsResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/sms/send": {
            "post": {
                "description": "Sends an SMS to the specified phone number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SMS"
                ],
                "summary": "Send an SMS",
                "parameters": [
                    {
                        "description": "SMS request payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SmsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sent SMS details",
                        "schema": {
                            "$ref": "#/definitions/model.SmsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/sms/status": {
            "post": {
                "description": "Returns the status of an SMS by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SMS"
                ],
                "summary": "Check SMS status",
                "parameters": [
                    {
                        "description": "SMS ID payload",
                        "name": "smsId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SmsId"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SMS status details",
                        "schema": {
                            "$ref": "#/definitions/model.SmsStatus"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CSRRequest": {
            "type": "object",
            "properties": {
                "csr": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "dto.CertificateResponse": {
            "type": "object",
            "properties": {
                "certificate": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "csr_id": {
                    "type": "integer"
                }
            }
        },
        "dto.SmsId": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "model.CsrRequest": {
            "type": "object",
            "properties": {
                "csr": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "service_name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "model.SmsRequest": {
            "type": "object",
            "properties": {
                "certificate": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "client_token": {
                    "type": "string"
                },
                "service_name": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "model.SmsResponse": {
            "type": "object",
            "properties": {
                "cost": {
                    "type": "number"
                },
                "date_created": {
                    "type": "integer"
                },
                "date_sent": {
                    "type": "integer"
                },
                "extend_status": {
                    "type": "string"
                },
                "from": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "number": {
                    "type": "string"
                },
                "raw": {},
                "service_id": {
                    "type": "string"
                },
                "service_name": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "model.SmsStatus": {
            "type": "object",
            "properties": {
                "extend_status": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "service_name": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
